events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    # =========================================================================
    # Servidor 1: Backend / Servidor de contenido (Práctica de la guía)
    # Escucha en el puerto 8080 y sirve archivos desde /data/up1
    # =========================================================================
    server {
        listen 8080;
        root /data/up1;

        location / {
            # Nginx buscará automáticamente index.html dentro de /data/up1
        }
    }

    # =========================================================================
    # Servidor 2: Proxy inverso y contenido estático (Práctica de la guía)
    # Escucha en el puerto 80
    # =========================================================================
    server {
        listen 80;

        # Cualquier petición general se redirige al servidor del puerto 8080
        location / {
            proxy_pass http://localhost:8080;
        }

        #Acceso limpio a la página de formulario
        location =  /formulario {
            proxy_pass http://localhost:8080/formulario.html;
        }

        # Cambio de busqueda de imágenes desde /data/images sin importa si hay subcarpetas
        location ~ \.(jpg|jpeg|png|gif|ico)$ {
            root /data/images;
        }
    }
}
