name: CI Practica Nginx

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validar configuración de Docker Compose
        run: docker compose config

      - name: Validar sintaxis de nginx.conf
        run: |
          docker run --rm -v ${{ github.workspace }}/nginx.conf:/etc/nginx/nginx.conf:ro -v ${{ github.workspace }}/data:/data:ro nginx:alpine nginx -t

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar dependencias y verificar sintaxis de Python
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          # Revisa que no haya errores de sintaxis o imports no resueltos
          flake8 data/conexion --count --select=E9,F63,F7,F82 --show-source --statistics
